package de.outerstellar.world;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for the WorldCitiesConverter pipeline.
 * Tests the full conversion process from PostgreSQL SQL to compressed H2 database.
 */
@Tag("integration")
class WorldCitiesConverterIntegrationTest {

    @TempDir
    Path tempDir;

    private Path postgresqlSql;
    private Path outputDb;

    @BeforeEach
    void setUp() throws IOException {
        // Create a sample PostgreSQL SQL file with minimal schema
        postgresqlSql = tempDir.resolve("world-postgresql.sql");
        Files.writeString(postgresqlSql, String.join("\n",
            "-- PostgreSQL dump",
            "CREATE TABLE countries (",
            "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
            "    name VARCHAR(255) NOT NULL,",
            "    iso2 CHAR(2),",
            "    capital VARCHAR(255),",
            "    population BIGINT",
            ");",
            "",
            "CREATE TABLE cities (",
            "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
            "    name VARCHAR(255) NOT NULL,",
            "    country_id BIGINT,",
            "    country_code CHAR(2),",
            "    latitude DOUBLE PRECISION,",
            "    longitude DOUBLE PRECISION,",
            "    population BIGINT",
            ");",
            "",
            "INSERT INTO countries (id, name, iso2, capital, population) VALUES",
            "    (1, 'Germany', 'DE', 'Berlin', 83000000),",
            "    (2, 'France', 'FR', 'Paris', 67000000),",
            "    (3, 'United States', 'US', 'Washington', 331000000);",
            "",
            "INSERT INTO cities (id, name, country_id, country_code, latitude, longitude, population) VALUES",
            "    (1, 'Berlin', 1, 'DE', 52.52, 13.405, 3645000),",
            "    (2, 'Hamburg', 1, 'DE', 53.5511, 9.9937, 1841000),",
            "    (3, 'Paris', 2, 'FR', 48.8566, 2.3522, 2161000),",
            "    (4, 'Lyon', 2, 'FR', 45.7640, 4.8357, 513000),",
            "    (5, 'New York', 3, 'US', 40.7128, -74.0060, 8336000);",
            ""
        ));

        outputDb = tempDir.resolve("world-cities");
    }

    @AfterEach
    void tearDown() throws IOException {
        // Cleanup database files
        Files.deleteIfExists(Path.of(outputDb + ".mv.db"));
        Files.deleteIfExists(Path.of(outputDb + ".trace.db"));
    }

    @Test
    void shouldConvertPostgresqlToH2WithDefaultOptions() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        // Verify database was created
        assertThat(Path.of(outputDb + ".mv.db")).exists();
        
        // Verify we can query the database using raw JDBC
        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM cities")) {
            
            assertThat(rs.next()).isTrue();
            assertThat(rs.getLong(1)).isEqualTo(5);
        }
        
        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM countries")) {
            
            assertThat(rs.next()).isTrue();
            assertThat(rs.getLong(1)).isEqualTo(3);
        }
    }

    @Test
    void shouldConvertWithCompactOption() throws IOException, SQLException {
        ConversionOptions options = ConversionOptions.builder()
            .compact(true)
            .workingDirectory(tempDir)
            .build();

        WorldCitiesConverter.convert(postgresqlSql, outputDb, options);

        // Verify database was created
        assertThat(Path.of(outputDb + ".mv.db")).exists();
        
        // In compact mode, we just verify the database exists and can be queried
        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM cities")) {
            
            assertThat(rs.next()).isTrue();
            long cityCount = rs.getLong(1);
            assertThat(cityCount).isGreaterThanOrEqualTo(0);
        }
    }

    @Test
    void shouldConvertWithGzipOption() throws IOException, SQLException {
        ConversionOptions options = ConversionOptions.builder()
            .gzipIntermediate(true)
            .workingDirectory(tempDir)
            .cleanupIntermediate(false)
            .build();

        WorldCitiesConverter.convert(postgresqlSql, outputDb, options);

        assertThat(Path.of(outputDb + ".mv.db")).exists();
        
        // Verify intermediate file was compressed
        Path gzippedSql = tempDir.resolve("world-cities-h2-converted.sql.gz");
        assertThat(gzippedSql).exists();
    }

    @Test
    void shouldQueryCitiesByName() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        // Use raw JDBC to verify data
        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM cities WHERE name = 'Berlin'")) {
            
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("name")).isEqualTo("Berlin");
            assertThat(rs.getString("country_code")).isEqualTo("DE");
        }
    }

    @Test
    void shouldQueryCitiesByCountryCode() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM cities WHERE country_code = 'DE' ORDER BY name")) {
            
            int count = 0;
            while (rs.next()) {
                count++;
                String name = rs.getString("name");
                assertThat(name).isIn("Berlin", "Hamburg");
            }
            assertThat(count).isEqualTo(2);
        }
    }

    @Test
    void shouldFindCountryByCode() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM countries WHERE iso2 = 'FR'")) {
            
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("name")).isEqualTo("France");
            assertThat(rs.getString("capital")).isEqualTo("Paris");
        }
    }

    @Test
    void shouldFindNearbyCities() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        // Search near Berlin (52.52, 13.405) within 500km
        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(
                 "SELECT name, (6371 * acos(cos(radians(52.52)) * cos(radians(latitude)) " +
                 "* cos(radians(longitude) - radians(13.405)) " +
                 "+ sin(radians(52.52)) * sin(radians(latitude)))) AS distance " +
                 "FROM cities WHERE latitude BETWEEN 50 AND 55 AND longitude BETWEEN 10 AND 15 " +
                 "ORDER BY distance")) {
            
            assertThat(rs.next()).isTrue();
            // Berlin should be closest
            assertThat(rs.getString("name")).isEqualTo("Berlin");
        }
    }

    @Test
    void shouldGetAllCountries() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM countries ORDER BY name")) {
            
            int count = 0;
            while (rs.next()) {
                count++;
            }
            assertThat(count).isEqualTo(3);
        }
    }

    @Test
    void shouldFindCityById() throws IOException, SQLException {
        WorldCitiesConverter.convert(postgresqlSql, outputDb);

        try (Connection conn = DriverManager.getConnection("jdbc:h2:file:" + outputDb, "sa", "");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT * FROM cities WHERE id = 1")) {
            
            assertThat(rs.next()).isTrue();
            assertThat(rs.getString("name")).isEqualTo("Berlin");
        }
    }
}
